events {}

http {
  server {
    listen 10000;

    location /api/ {
      proxy_pass http://127.0.0.1:8000/;
    }

    location /grafana/ {
      proxy_pass http://127.0.0.1:3000/;
      proxy_set_header Host $host;
    }

    location /prometheus/ {
      proxy_pass http://127.0.0.1:9090/;
    }
  }
}
