[supervisord]
nodaemon=true

[program:api]
command=uvicorn src.app.main:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true
priority=20

[program:grafana]
command=/usr/sbin/grafana-server \
  --homepath=/usr/share/grafana \
  --config=/etc/grafana/grafana.ini
autostart=true
autorestart=true
priority=30

[program:prometheus]
command=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml
autostart=true
autorestart=true
priority=40

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10