[supervisord]
nodaemon=true

[program:api]
command=uvicorn src.app.main:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true

[program:grafana]
command=/usr/sbin/grafana-server --homepath=/usr/share/grafana
autostart=true
autorestart=true

[program:prometheus]
command=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml
autostart=true
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
